export const PRODUCTION_STEPS = {
  TABLE_WIDTH: 2600,
  FIRST_COL_WIDTH: 500,
  FIRST_COL_PADDING_LEFT: 80,
  COL_PADDING_LEFT: 32
};
export const COLORS = {
  PRODUCTION_STEPS_BLUE: "#E3F2FD",
  PRODUCTION_STEPS_TEXT_GREY: "#414141"
};
